### ISSUE TITLE
find_subscribe fails to notify on QEMU bridge network

### ISSUE THREAD

**Issue by svit19** [afflux/pysomeip#13]
I am running QNX 7.1 on QEMU. I am running simpleservice example in it and trying to connect from host (Tried on both Windows and WSL)
The subscribe seems to succeed since I am seeing ACK on client side but no notifications are being sent by service. Instead the service seems to cyclically end up with exception "servname not supported for ai_socktype".

### Service on QNX
```
# python simpleservice.py --multicast 224.224.224.245 192.168.0.11
2023-08-29 13:12:07,895 INFO     root: install coloredlogs for colored logs :-)
2023-08-29 13:12:55,787 INFO     someip.service-b0a7-0001: client_subscribed from ('192.168.0.3', 30490): EventgroupSubscription(service_id=45223, instance_id=1,
 major_version=1, id=1, counter=0, ttl=5, endpoints=frozenset({IPv4EndpointOption(address=IPv4Address('192.168.0.3'), l4proto=<L4Protocols.UDP: 17>, port=38511)}
), options=())
2023-08-29 13:12:56,108 ERROR    someip.service-b0a7-0001.evgrp-0001: unhandled exception in SimpleEventgroup._notify_single
Traceback (most recent call last):
  File "/data/home/root/.local/lib/python3.8/site-packages/someip/utils.py", line 24, in wrapper
    return await f(self, *args, **kwargs)
  File "/data/home/root/.local/lib/python3.8/site-packages/someip/service.py", line 70, in _notify_single
    addr = await endpoint.addrinfo()
  File "/data/home/root/.local/lib/python3.8/site-packages/someip/header.py", line 811, in addrinfo
    addr = await someip.utils.getfirstaddrinfo(
  File "/data/home/root/.local/lib/python3.8/site-packages/someip/utils.py", line 63, in getfirstaddrinfo
    result = await loop.getaddrinfo(
  File "/system/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/system/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/system/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
**socket.gaierror: [Errno 9] servname not supported for ai_socktype**
```
### Subscriber on host
```
:~ python find-subscribe.py 192.168.0.3 224.224.224.245 38511 0xb0a7 1                                       
2023-08-29 13:12:55,876 INFO     root: install coloredlogs for colored logs :-)
2023-08-29 13:12:55,883 DEBUG    asyncio: Using selector: EpollSelector
2023-08-29 13:12:56,791 DEBUG    someip.sd: sd_message_received received from 192.168.0.11:30490 (multicast=True): reboot=True, unicast=True, entries:
type=OfferService, service=0xb0a7, instance=0x0001, version=1.0, ttl=3,  options_1=[192.168.0.11:38510 (UDP)], options_2=[]
2023-08-29 13:12:56,852 DEBUG    someip.sd: sd_message_received received from 192.168.0.11:30490 (multicast=False): reboot=True, unicast=True, entries:
type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=5,  options_1=[], options_2=[]
2023-08-29 13:12:56,853 INFO     someip.sd: received Subscribe ACK from ('192.168.0.11', 30490): type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, e
ventgroup_counter=0, eventgroup_id=1, ttl=5,  options_1=[], options_2=[]
```

However when I swap the service and subscriber it is success!

### Service on host
```
> python simpleservice.py --multicast 224.224.224.245 192.168.7.10
DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(
2023-08-29 18:59:32,274 INFO     someip.service-b0a7-0001: client_subscribed from ('192.168.7.11', 30490): EventgroupSubscription(service_id=45223, instance_id=1, major_version=1, id=1, counter=0, ttl=5, endpoints=frozenset({IPv4EndpointOption(address=IPv4Address('192.168.7.11'), l4proto=<L4Protocols.UDP: 17>, port=38511)}), options=())
2023-08-29 18:59:32,275 INFO     someip.service-b0a7-0001.evgrp-0001: initial notify 0x0001 to ('192.168.7.11', 38511): b'2023-08-29T18:59:31.815165'
2023-08-29 18:59:33,268 INFO     someip.service-b0a7-0001.evgrp-0001: cyclic notify 0x0001 to ('192.168.7.11', 38511): b'2023-08-29T18:59:32.737022'
2023-08-29 18:59:34,281 INFO     someip.service-b0a7-0001.evgrp-0001: cyclic notify 0x0001 to ('192.168.7.11', 38511): b'2023-08-29T18:59:33.644849'
```

### Subscriber on QNX
```
# python find-subscribe.py 192.168.7.11 224.224.224.245 38511 0xb0a7 1
2023-08-29 13:27:36,934 INFO     root: install coloredlogs for colored logs :-)
2023-08-29 13:27:37,183 DEBUG    asyncio: Using selector: PollSelector
2023-08-29 13:27:38,068 DEBUG    someip.sd: sd_message_received received from 192.168.7.10:30490 (multicast=True): reboot=True, unicast=True, entries:
type=OfferService, service=0xb0a7, instance=0x0001, version=1.0, ttl=3,  options_1=[192.168.7.10:38510 (UDP)], options_2=[]
2023-08-29 13:27:38,102 DEBUG    someip.sd: sd_message_received received from 192.168.7.10:30490 (multicast=False): reboot=True, unicast=True, entries:
type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=5,  options_1=[], options_2=[]
2023-08-29 13:27:38,111 INFO     someip.sd: received Subscribe ACK from ('192.168.7.10', 30490): type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=5,  options_1=[], options_2=[]
2023-08-29 13:27:38,121 INFO     notification: service=0xb0a7 method=0x8001 interface_version=0x01 returncode=E_OK payload=32 30 32 33 2d 30 38 2d 32 39 54 31 38 3a 35 39 3a 33 31 2e 38 31 35 31 36 35
2023-08-29 13:27:38,929 INFO     notification: service=0xb0a7 method=0x8001 interface_version=0x01 returncode=E_OK payload=32 30 32 33 2d 30 38 2d 32 39 54 31 38 3a 35 39 3a 33 32 2e 37 33 37 30 32 32
```
Subscribe failed initially with NACK. But I am now successful when both service and subscriber run on host.  I don't remember what exactly I had changed then. Putting those logs here for reference.

### Service on host (WSL)
```
# python ../simpleservice.py --multicast 224.224.224.245 192.168.0.3
2023-08-29 16:55:06,459 INFO     root: install coloredlogs for colored logs :-)
/mnt/c/Users/svitthal/Codes/SIL_CCCM_EVA25_TAMS-1165_PCOM-QNX/environment_readiness_tests/test_cases/some_ip/ubuntu/../simpleservice.py:118: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(
2023-08-29 16:55:14,267 INFO     someip.sd.announce: received from 192.168.0.3:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 16:55:14,316 INFO     someip.sd.announce: received from 192.168.0.3:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 16:56:07,756 INFO     someip.sd.announce: received from 192.168.0.3:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 16:56:07,805 INFO     someip.sd.announce: received from 192.168.0.3:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
```

### Subscriber on host (WSL)
```
python ../find-subscribe.py 172.19.247.232 224.224.224.245 38511 0xb0a7 1
2023-08-29 18:37:20,463 INFO     root: install coloredlogs for colored logs :-)
/mnt/c/Users/svitthal/Codes/SIL_CCCM_EVA25_TAMS-1165_PCOM-QNX/environment_readiness_tests/test_cases/some_ip/ubuntu/../find-subscribe.py:111: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(
2023-08-29 18:37:20,478 DEBUG    asyncio: Using selector: EpollSelector
2023-08-29 18:37:21,705 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=True): reboot=True, unicast=True, entries:
type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 18:37:21,705 INFO     someip.sd.announce: received from 172.19.247.232:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 18:37:21,776 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=True): reboot=True, unicast=True, entries:
type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 18:37:21,776 INFO     someip.sd.announce: received from 172.19.247.232:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 18:37:21,778 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=False): reboot=True, unicast=True, entries:
type=OfferService, service=0xb0a7, instance=0x0001, version=1.0, ttl=3,  options_1=[172.19.247.232:38510 (UDP)], options_2=[]
2023-08-29 18:37:21,778 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=True): reboot=True, unicast=True, entries:
type=OfferService, service=0xb0a7, instance=0x0001, version=1.0, ttl=3,  options_1=[172.19.247.232:38510 (UDP)], options_2=[]
2023-08-29 18:37:21,779 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=False): reboot=True, unicast=True, entries:
type=Subscribe, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=5,  options_1=[172.19.247.232:38511 (UDP)], options_2=[]
2023-08-29 18:37:21,780 WARNING  someip.sd.announce: discarding subscribe for unknown service from 172.19.247.232:30490: type=Subscribe, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=5,  options_1=[172.19.247.232:38511 (UDP)], options_2=[]
2023-08-29 18:37:21,780 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=False): reboot=True, unicast=True, entries:
type=Subscribe, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=0,  options_1=[172.19.247.232:38511 (UDP)], options_2=[]
2023-08-29 18:37:21,781 WARNING  someip.sd.announce: discarding subscribe for unknown service from 172.19.247.232:30490: type=Subscribe, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=0,  options_1=[172.19.247.232:38511 (UDP)], options_2=[]
2023-08-29 18:37:21,846 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=False): reboot=True, unicast=True, entries:
type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=0,  options_1=[], options_2=[]
type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=0,  options_1=[], options_2=[]
2023-08-29 18:37:21,846 INFO     someip.sd: received Subscribe NACK from ('172.19.247.232', 30490): type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=0,  options_1=[], options_2=[]
2023-08-29 18:37:21,846 INFO     someip.sd: received Subscribe NACK from ('172.19.247.232', 30490): type=SubscribeAck, service=0xb0a7, instance=0x0001, version=1, eventgroup_counter=0, eventgroup_id=1, ttl=0,  options_1=[], options_2=[]
2023-08-29 18:37:21,847 DEBUG    someip.sd: sd_message_received received from 172.19.247.232:30490 (multicast=True): reboot=True, unicast=True, entries:
type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 18:37:21,847 INFO     someip.sd.announce: received from 172.19.247.232:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
```
Can you help me find why the QEMU service-host client scenario is failing?

**Comment by afflux** [comment]
It seems like getaddrinfo is quite limited on QNX. Can you please apply 
the fixes from branch `bugfix/qnx-gai` (413aecc135) and see if it solves 
the issue?

**Comment by svit19** [comment]
Great! Thanks for the quick(est) fix! It works like a charm. Below are the logs for reference (celebration).

```
# python simpleservice.py --multicast 224.224.224.245 192.168.7.11
2023-08-29 16:01:00,643 INFO     root: install coloredlogs for colored logs :-)
2023-08-29 16:01:10,871 INFO     someip.sd.announce: received from 192.168.7.10:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 16:01:10,887 INFO     someip.sd.announce: received from 192.168.7.10:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 16:01:10,896 INFO     someip.sd.announce: received from 192.168.7.10:30490: type=FindService, service=0xb0a7, instance=0xffff, version=255.4294967295, ttl=3,  options_1=[], options_2=[]
2023-08-29 16:01:10,931 INFO     someip.service-b0a7-0001: client_subscribed from ('192.168.7.10', 30490): EventgroupSubscription(service_id=45223, instance_id=1, major_version=1, id=1, counter=0, ttl=5, endpoints=frozenset({IPv4EndpointOption(address=IPv4Address('192.168.7.10'), l4proto=<L4Protocols.UDP: 17>, port=38511)}), options=())
2023-08-29 16:01:11,000 INFO     someip.service-b0a7-0001.evgrp-0001: initial notify 0x0001 to ('192.168.7.10', 38511): b'2023-08-29T16:01:10.127000'
2023-08-29 16:01:11,958 INFO     someip.service-b0a7-0001.evgrp-0001: cyclic notify 0x0001 to ('192.168.7.10', 38511): b'2023-08-29T16:01:11.932000'
2023-08-29 16:01:12,975 INFO     someip.service-b0a7-0001.evgrp-0001: cyclic notify 0x0001 to ('192.168.7.10', 38511): b'2023-08-29T16:01:12.834000'
```

```
python ..\find-subscribe.py 192.168.7.10 224.224.224.245 38511 0xb0a7 1
...find-subscribe.py:111: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(
2023-08-29 21:32:08,321 DEBUG    asyncio: Using proactor: IocpProactor
2023-08-29 21:32:08,790 INFO     notification: service=0xb0a7 method=0x8001 interface_version=0x01 returncode=E_OK payload=32 30 32 33 2d 30 38 2d 32 39 54 31 36 3a 30 31 3a 31 30 2e 31 32 37 30 30 30
2023-08-29 21:32:09,963 INFO     notification: service=0xb0a7 method=0x8001 interface_version=0x01 returncode=E_OK payload=32 30 32 33 2d 30 38 2d 32 39 54 31 36 3a 30 31 3a 31 31 2e 39 33 32 30 30 30
```

**Comment by afflux** [comment]
Reopening this until I've applied the fix to the master branch
